from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..errors import AppError, ErrorCode, ExitCode

MANIFEST_FILENAME = "remix_project.json"
SCHEMA_VERSION = 1


def remix_error(message: str, hint: str) -> AppError:
    return AppError(
        error_code=ErrorCode.INVALID_ARGUMENT,
        message=message,
        hint=hint,
        exit_code=ExitCode.INVALID_ARGUMENT,
    )


def resolve_manifest_path(project: str | Path) -> Path:
    path = Path(project).expanduser()
    if path.suffix == ".json":
        return path
    return path / MANIFEST_FILENAME


def _default_manifest(*, source_audio_path: Path, rights_status: str) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "source_audio_path": str(source_audio_path.expanduser().resolve()),
        "rights_status": rights_status,
        "detected_bpm": None,
        "target_bpm": None,
        "detected_key": None,
        "target_key": None,
        "time_signature": "4/4",
        "sections": [],
        "assets": [],
        "stems": [],
        "arrangement_plan": None,
        "ableton_track_refs": {},
        "generated_assets": [],
    }


def init_manifest(
    *,
    source_audio_path: str | Path,
    project: str | Path,
    rights_status: str = "unspecified",
) -> Path:
    source = Path(source_audio_path).expanduser()
    if not source.is_absolute():
        raise remix_error(
            message=f"source_audio_path must be absolute, got {str(source)!r}",
            hint="Pass an absolute path to --source.",
        )
    manifest_path = resolve_manifest_path(project)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = _default_manifest(source_audio_path=source, rights_status=rights_status.strip())
    save_manifest(manifest_path, manifest)
    return manifest_path


def load_manifest(project: str | Path) -> dict[str, Any]:
    manifest_path = resolve_manifest_path(project)
    if not manifest_path.exists():
        raise remix_error(
            message=f"remix manifest not found: {manifest_path}",
            hint="Run 'ableton-cli remix init' first or pass the manifest JSON path.",
        )
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise remix_error(
            message=f"remix manifest is not valid JSON: {manifest_path}",
            hint="Fix remix_project.json before retrying.",
        ) from exc
    if not isinstance(payload, dict):
        raise remix_error(
            message="remix manifest root must be an object",
            hint="Use a remix_project.json object generated by 'remix init'.",
        )
    if payload.get("schema_version") != SCHEMA_VERSION:
        raise remix_error(
            message=f"unsupported remix schema_version: {payload.get('schema_version')!r}",
            hint=f"Use schema_version {SCHEMA_VERSION}.",
        )
    return payload


def save_manifest(project: str | Path, manifest: dict[str, Any]) -> Path:
    manifest_path = resolve_manifest_path(project)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest_path


def inspect_manifest(project: str | Path) -> dict[str, Any]:
    manifest_path = resolve_manifest_path(project)
    manifest = load_manifest(manifest_path)
    return {
        "project": str(manifest_path),
        "schema_version": manifest["schema_version"],
        "source_audio_path": manifest["source_audio_path"],
        "rights_status": manifest.get("rights_status", "unspecified"),
        "asset_count": len(manifest.get("assets", [])),
        "stem_count": len(manifest.get("stems", [])),
        "section_count": len(manifest.get("sections", [])),
        "has_arrangement_plan": manifest.get("arrangement_plan") is not None,
        "target_bpm": manifest.get("target_bpm"),
        "target_key": manifest.get("target_key"),
    }


def set_target(project: str | Path, *, bpm: float | None, key: str | None) -> dict[str, Any]:
    manifest_path = resolve_manifest_path(project)
    manifest = load_manifest(manifest_path)
    if bpm is not None:
        if bpm <= 0:
            raise remix_error(
                message=f"bpm must be > 0, got {bpm}",
                hint="Pass a positive --bpm value.",
            )
        manifest["target_bpm"] = float(bpm)
    if key is not None:
        parsed_key = key.strip()
        if not parsed_key:
            raise remix_error(message="key must not be empty", hint="Pass a non-empty --key.")
        manifest["target_key"] = parsed_key
    save_manifest(manifest_path, manifest)
    return {
        "project": str(manifest_path),
        "target_bpm": manifest["target_bpm"],
        "target_key": manifest["target_key"],
    }
