"""Generated by tools/generate_client_methods.py. Do not edit.

Every method here is a pass-through: it forwards its arguments to a remote
command and returns the response untouched. The source of truth is
``CLIENT_METHOD_SPECS`` in ``ableton_cli.command_registry``; regenerate with::

    uv run python tools/generate_client_methods.py

Client methods that assemble arguments, branch, or post-process are not
generated — they live hand-written in the sibling ``_client_*`` mixins.
"""

from __future__ import annotations

from typing import Any

from ..refs import RefPayload

__all__ = ["_AbletonClientGeneratedMixin"]


class _AbletonClientGeneratedMixin:
    """Pass-through remote calls. See module docstring."""

    _call: Any

    def arrangement_clip_file_replace(
        self, track: int, index: int, audio_path: str
    ) -> dict[str, Any]:
        return self._call(
            "arrangement_clip_file_replace",
            {"track": track, "index": index, "audio_path": audio_path},
        )

    def arrangement_clip_gain_set(self, track: int, index: int, db: float) -> dict[str, Any]:
        return self._call("arrangement_clip_gain_set", {"track": track, "index": index, "db": db})

    def arrangement_clip_loop_set(
        self, track: int, index: int, start: float, end: float, enabled: bool
    ) -> dict[str, Any]:
        return self._call(
            "arrangement_clip_loop_set",
            {"track": track, "index": index, "start": start, "end": end, "enabled": enabled},
        )

    def arrangement_clip_marker_set(
        self, track: int, index: int, start_marker: float, end_marker: float
    ) -> dict[str, Any]:
        return self._call(
            "arrangement_clip_marker_set",
            {
                "track": track,
                "index": index,
                "start_marker": start_marker,
                "end_marker": end_marker,
            },
        )

    def arrangement_clip_props_get(self, track: int, index: int) -> dict[str, Any]:
        return self._call("arrangement_clip_props_get", {"track": track, "index": index})

    def arrangement_clip_transpose_set(
        self, track: int, index: int, semitones: int
    ) -> dict[str, Any]:
        return self._call(
            "arrangement_clip_transpose_set",
            {"track": track, "index": index, "semitones": semitones},
        )

    def arrangement_clip_warp_get(self, track: int, index: int) -> dict[str, Any]:
        return self._call("arrangement_clip_warp_get", {"track": track, "index": index})

    def arrangement_from_session(self, scenes: list[dict[str, float]]) -> dict[str, Any]:
        return self._call("arrangement_from_session", {"scenes": scenes})

    def arrangement_record_start(self) -> dict[str, Any]:
        return self._call("arrangement_record_start")

    def arrangement_record_stop(self) -> dict[str, Any]:
        return self._call("arrangement_record_stop")

    def clip_active_get(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_active_get", {"track": track, "clip": clip})

    def clip_active_set(self, track: int, clip: int, value: bool) -> dict[str, Any]:
        return self._call("clip_active_set", {"track": track, "clip": clip, "value": value})

    def clip_envelope_set(
        self,
        track: int,
        clip: int,
        device_ref: RefPayload,
        parameter_ref: RefPayload,
        points: list[dict[str, float]],
        mode: str = "replace",
    ) -> dict[str, Any]:
        return self._call(
            "clip_envelope_set",
            {
                "track": track,
                "clip": clip,
                "device_ref": device_ref,
                "parameter_ref": parameter_ref,
                "points": points,
                "mode": mode,
            },
        )

    def clip_file_path_get(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_file_path_get", {"track": track, "clip": clip})

    def clip_file_replace(self, track: int, clip: int, audio_path: str) -> dict[str, Any]:
        return self._call(
            "clip_file_replace", {"track": track, "clip": clip, "audio_path": audio_path}
        )

    def clip_gain_set(self, track: int, clip: int, db: float) -> dict[str, Any]:
        return self._call("clip_gain_set", {"track": track, "clip": clip, "db": db})

    def clip_groove_amount_set(self, track: int, clip: int, value: float) -> dict[str, Any]:
        return self._call("clip_groove_amount_set", {"track": track, "clip": clip, "value": value})

    def clip_groove_clear(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_groove_clear", {"track": track, "clip": clip})

    def clip_groove_get(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_groove_get", {"track": track, "clip": clip})

    def clip_groove_set(self, track: int, clip: int, target: str) -> dict[str, Any]:
        return self._call("clip_groove_set", {"track": track, "clip": clip, "target": target})

    def clip_loop_set(
        self, track: int, clip: int, start: float, end: float, enabled: bool
    ) -> dict[str, Any]:
        return self._call(
            "clip_loop_set",
            {"track": track, "clip": clip, "start": start, "end": end, "enabled": enabled},
        )

    def clip_marker_set(
        self, track: int, clip: int, start_marker: float, end_marker: float
    ) -> dict[str, Any]:
        return self._call(
            "clip_marker_set",
            {"track": track, "clip": clip, "start_marker": start_marker, "end_marker": end_marker},
        )

    def clip_props_get(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_props_get", {"track": track, "clip": clip})

    def clip_transpose_set(self, track: int, clip: int, semitones: int) -> dict[str, Any]:
        return self._call(
            "clip_transpose_set", {"track": track, "clip": clip, "semitones": semitones}
        )

    def clip_warp_get(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_warp_get", {"track": track, "clip": clip})

    def clip_warp_marker_list(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("clip_warp_marker_list", {"track": track, "clip": clip})

    def clip_warp_marker_move(
        self, track: int, clip: int, beat_time: float, distance: float
    ) -> dict[str, Any]:
        return self._call(
            "clip_warp_marker_move",
            {"track": track, "clip": clip, "beat_time": beat_time, "distance": distance},
        )

    def clip_warp_marker_remove(self, track: int, clip: int, beat_time: float) -> dict[str, Any]:
        return self._call(
            "clip_warp_marker_remove", {"track": track, "clip": clip, "beat_time": beat_time}
        )

    def create_audio_track(self, index: int = -1) -> dict[str, Any]:
        return self._call("create_audio_track", {"index": index})

    def create_clip(self, track: int, clip: int, length: float) -> dict[str, Any]:
        return self._call("create_clip", {"track": track, "clip": clip, "length": length})

    def create_midi_track(self, index: int = -1) -> dict[str, Any]:
        return self._call("create_midi_track", {"index": index})

    def create_scene(self, index: int) -> dict[str, Any]:
        return self._call("create_scene", {"index": index})

    def device_chains_list(self, track_ref: RefPayload, device_ref: RefPayload) -> dict[str, Any]:
        return self._call("device_chains_list", {"track_ref": track_ref, "device_ref": device_ref})

    def device_macro_list(self, track_ref: RefPayload, device_ref: RefPayload) -> dict[str, Any]:
        return self._call("device_macro_list", {"track_ref": track_ref, "device_ref": device_ref})

    def device_macro_set(
        self, track_ref: RefPayload, device_ref: RefPayload, macro_index: int, value: float
    ) -> dict[str, Any]:
        return self._call(
            "device_macro_set",
            {
                "track_ref": track_ref,
                "device_ref": device_ref,
                "macro_index": macro_index,
                "value": value,
            },
        )

    def execute_batch(self, steps: list[dict[str, Any]]) -> dict[str, Any]:
        return self._call("execute_batch", {"steps": steps})

    def fire_clip(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("fire_clip", {"track": track, "clip": clip})

    def fire_scene(self, scene: int) -> dict[str, Any]:
        return self._call("fire_scene", {"scene": scene})

    def get_browser_categories(self, category_type: str = "all") -> dict[str, Any]:
        return self._call("get_browser_categories", {"category_type": category_type})

    def get_browser_items(
        self, path: str, item_type: str = "all", limit: int = 100, offset: int = 0
    ) -> dict[str, Any]:
        return self._call(
            "get_browser_items",
            {"path": path, "item_type": item_type, "limit": limit, "offset": offset},
        )

    def get_browser_items_at_path(self, path: str) -> dict[str, Any]:
        return self._call("get_browser_items_at_path", {"path": path})

    def get_browser_tree(self, category_type: str = "all") -> dict[str, Any]:
        return self._call("get_browser_tree", {"category_type": category_type})

    def get_session_info(self) -> dict[str, object]:
        return self._call("get_session_info")

    def get_track_info(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("get_track_info", {"track_ref": track_ref})

    def list_effect_parameters(
        self, track_ref: RefPayload, device_ref: RefPayload
    ) -> dict[str, Any]:
        return self._call(
            "list_effect_parameters", {"track_ref": track_ref, "device_ref": device_ref}
        )

    def list_standard_effect_keys(self, effect_type: str) -> dict[str, Any]:
        return self._call("list_standard_effect_keys", {"effect_type": effect_type})

    def list_standard_synth_keys(self, synth_type: str) -> dict[str, Any]:
        return self._call("list_standard_synth_keys", {"synth_type": synth_type})

    def list_synth_parameters(
        self, track_ref: RefPayload, device_ref: RefPayload
    ) -> dict[str, Any]:
        return self._call(
            "list_synth_parameters", {"track_ref": track_ref, "device_ref": device_ref}
        )

    def master_device_delete(self, device_index: int) -> dict[str, Any]:
        return self._call("master_device_delete", {"device_index": device_index})

    def master_device_load(self, target: str, position: str) -> dict[str, Any]:
        return self._call("master_device_load", {"target": target, "position": position})

    def master_device_move(self, device_index: int, to_index: int) -> dict[str, Any]:
        return self._call(
            "master_device_move", {"device_index": device_index, "to_index": to_index}
        )

    def master_device_parameter_set(
        self, device_ref: dict[str, Any], parameter_ref: dict[str, Any], value: float
    ) -> dict[str, Any]:
        return self._call(
            "master_device_parameter_set",
            {"device_ref": device_ref, "parameter_ref": parameter_ref, "value": value},
        )

    def master_device_parameters_list(self, device_ref: dict[str, Any]) -> dict[str, Any]:
        return self._call("master_device_parameters_list", {"device_ref": device_ref})

    def master_devices_list(self) -> dict[str, Any]:
        return self._call("master_devices_list")

    def master_effect_keys(self, effect_type: str) -> dict[str, Any]:
        return self._call("master_effect_keys", {"effect_type": effect_type})

    def master_effect_observe(self, effect_type: str, device_ref: dict[str, Any]) -> dict[str, Any]:
        return self._call(
            "master_effect_observe", {"effect_type": effect_type, "device_ref": device_ref}
        )

    def master_effect_set(
        self,
        effect_type: str,
        device_ref: dict[str, Any],
        parameter_ref: dict[str, Any],
        value: float,
    ) -> dict[str, Any]:
        return self._call(
            "master_effect_set",
            {
                "effect_type": effect_type,
                "device_ref": device_ref,
                "parameter_ref": parameter_ref,
                "value": value,
            },
        )

    def master_info(self) -> dict[str, Any]:
        return self._call("master_info")

    def master_panning_get(self) -> dict[str, Any]:
        return self._call("master_panning_get")

    def master_panning_set(self, value: float) -> dict[str, Any]:
        return self._call("master_panning_set", {"value": value})

    def master_volume_get(self) -> dict[str, Any]:
        return self._call("master_volume_get")

    def master_volume_set(self, value: float) -> dict[str, Any]:
        return self._call("master_volume_set", {"value": value})

    def mixer_crossfader_get(self) -> dict[str, Any]:
        return self._call("mixer_crossfader_get")

    def mixer_crossfader_set(self, value: float) -> dict[str, Any]:
        return self._call("mixer_crossfader_set", {"value": value})

    def mixer_cue_routing_get(self) -> dict[str, Any]:
        return self._call("mixer_cue_routing_get")

    def mixer_cue_routing_set(self, routing: str) -> dict[str, Any]:
        return self._call("mixer_cue_routing_set", {"routing": routing})

    def mixer_cue_volume_get(self) -> dict[str, Any]:
        return self._call("mixer_cue_volume_get")

    def mixer_cue_volume_set(self, value: float) -> dict[str, Any]:
        return self._call("mixer_cue_volume_set", {"value": value})

    def observe_effect_parameters(
        self, track_ref: RefPayload, device_ref: RefPayload
    ) -> dict[str, Any]:
        return self._call(
            "observe_effect_parameters", {"track_ref": track_ref, "device_ref": device_ref}
        )

    def observe_standard_effect_state(
        self, effect_type: str, track_ref: RefPayload, device_ref: RefPayload
    ) -> dict[str, Any]:
        return self._call(
            "observe_standard_effect_state",
            {"effect_type": effect_type, "track_ref": track_ref, "device_ref": device_ref},
        )

    def observe_standard_synth_state(
        self, synth_type: str, track_ref: RefPayload, device_ref: RefPayload
    ) -> dict[str, Any]:
        return self._call(
            "observe_standard_synth_state",
            {"synth_type": synth_type, "track_ref": track_ref, "device_ref": device_ref},
        )

    def observe_synth_parameters(
        self, track_ref: RefPayload, device_ref: RefPayload
    ) -> dict[str, Any]:
        return self._call(
            "observe_synth_parameters", {"track_ref": track_ref, "device_ref": device_ref}
        )

    def ping(self) -> dict[str, object]:
        return self._call("ping")

    def return_track_mute_get(self, return_track: int) -> dict[str, Any]:
        return self._call("return_track_mute_get", {"return_track": return_track})

    def return_track_mute_set(self, return_track: int, value: bool) -> dict[str, Any]:
        return self._call("return_track_mute_set", {"return_track": return_track, "value": value})

    def return_track_solo_get(self, return_track: int) -> dict[str, Any]:
        return self._call("return_track_solo_get", {"return_track": return_track})

    def return_track_solo_set(self, return_track: int, value: bool) -> dict[str, Any]:
        return self._call("return_track_solo_set", {"return_track": return_track, "value": value})

    def return_track_volume_get(self, return_track: int) -> dict[str, Any]:
        return self._call("return_track_volume_get", {"return_track": return_track})

    def return_track_volume_set(self, return_track: int, value: float) -> dict[str, Any]:
        return self._call("return_track_volume_set", {"return_track": return_track, "value": value})

    def return_tracks_list(self) -> dict[str, Any]:
        return self._call("return_tracks_list")

    def scenes_list(self) -> dict[str, Any]:
        return self._call("scenes_list")

    def scenes_move(self, from_index: int, to_index: int) -> dict[str, Any]:
        return self._call("scenes_move", {"from": from_index, "to": to_index})

    def session_snapshot(self) -> dict[str, object]:
        return self._call("session_snapshot")

    def set_clip_name(self, track: int, clip: int, name: str) -> dict[str, Any]:
        return self._call("set_clip_name", {"track": track, "clip": clip, "name": name})

    def set_scene_name(self, scene: int, name: str) -> dict[str, Any]:
        return self._call("set_scene_name", {"scene": scene, "name": name})

    def set_tempo(self, tempo: float) -> dict[str, object]:
        return self._call("set_tempo", {"tempo": tempo})

    def set_track_name(self, track_ref: RefPayload, name: str) -> dict[str, Any]:
        return self._call("set_track_name", {"track_ref": track_ref, "name": name})

    def song_export_audio(self, path: str) -> dict[str, object]:
        return self._call("song_export_audio", {"path": path})

    def song_info(self) -> dict[str, object]:
        return self._call("song_info")

    def song_new(self) -> dict[str, object]:
        return self._call("song_new")

    def song_redo(self) -> dict[str, object]:
        return self._call("song_redo")

    def song_save(self, path: str) -> dict[str, object]:
        return self._call("song_save", {"path": path})

    def song_undo(self) -> dict[str, object]:
        return self._call("song_undo")

    def start_playback(self) -> dict[str, object]:
        return self._call("start_playback")

    def stop_all_clips(self) -> dict[str, Any]:
        return self._call("stop_all_clips")

    def stop_clip(self, track: int, clip: int) -> dict[str, Any]:
        return self._call("stop_clip", {"track": track, "clip": clip})

    def stop_playback(self) -> dict[str, object]:
        return self._call("stop_playback")

    def track_arm_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_arm_get", {"track_ref": track_ref})

    def track_arm_set(self, track_ref: RefPayload, value: bool) -> dict[str, Any]:
        return self._call("track_arm_set", {"track_ref": track_ref, "value": value})

    def track_mute_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_mute_get", {"track_ref": track_ref})

    def track_mute_set(self, track_ref: RefPayload, value: bool) -> dict[str, Any]:
        return self._call("track_mute_set", {"track_ref": track_ref, "value": value})

    def track_panning_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_panning_get", {"track_ref": track_ref})

    def track_panning_set(self, track_ref: RefPayload, value: float) -> dict[str, Any]:
        return self._call("track_panning_set", {"track_ref": track_ref, "value": value})

    def track_routing_input_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_routing_input_get", {"track_ref": track_ref})

    def track_routing_input_set(
        self, track_ref: RefPayload, routing_type: str, routing_channel: str | None
    ) -> dict[str, Any]:
        return self._call(
            "track_routing_input_set",
            {
                "track_ref": track_ref,
                "routing_type": routing_type,
                "routing_channel": routing_channel,
            },
        )

    def track_routing_output_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_routing_output_get", {"track_ref": track_ref})

    def track_routing_output_set(
        self, track_ref: RefPayload, routing_type: str, routing_channel: str
    ) -> dict[str, Any]:
        return self._call(
            "track_routing_output_set",
            {
                "track_ref": track_ref,
                "routing_type": routing_type,
                "routing_channel": routing_channel,
            },
        )

    def track_send_get(self, track_ref: RefPayload, send: int) -> dict[str, Any]:
        return self._call("track_send_get", {"track_ref": track_ref, "send": send})

    def track_send_set(self, track_ref: RefPayload, send: int, value: float) -> dict[str, Any]:
        return self._call("track_send_set", {"track_ref": track_ref, "send": send, "value": value})

    def track_solo_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_solo_get", {"track_ref": track_ref})

    def track_solo_set(self, track_ref: RefPayload, value: bool) -> dict[str, Any]:
        return self._call("track_solo_set", {"track_ref": track_ref, "value": value})

    def track_volume_get(self, track_ref: RefPayload) -> dict[str, Any]:
        return self._call("track_volume_get", {"track_ref": track_ref})

    def track_volume_set(self, track_ref: RefPayload, value: float) -> dict[str, Any]:
        return self._call("track_volume_set", {"track_ref": track_ref, "value": value})

    def tracks_delete(self, track: int) -> dict[str, Any]:
        return self._call("tracks_delete", {"track": track})

    def tracks_list(self) -> dict[str, Any]:
        return self._call("tracks_list")

    def transport_play(self) -> dict[str, object]:
        return self._call("transport_play")

    def transport_position_get(self) -> dict[str, object]:
        return self._call("transport_position_get")

    def transport_position_set(self, beats: float) -> dict[str, object]:
        return self._call("transport_position_set", {"beats": beats})

    def transport_rewind(self) -> dict[str, object]:
        return self._call("transport_rewind")

    def transport_stop(self) -> dict[str, object]:
        return self._call("transport_stop")

    def transport_tempo_get(self) -> dict[str, object]:
        return self._call("transport_tempo_get")

    def transport_tempo_set(self, bpm: float) -> dict[str, object]:
        return self._call("transport_tempo_set", {"bpm": bpm})

    def transport_toggle(self) -> dict[str, object]:
        return self._call("transport_toggle")
