from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

import typer

from ..runtime import execute_command, get_client
from ..session_diff import compute_session_diff
from ._client_command_runner import CommandSpec
from ._client_command_runner import run_client_command as run_client_command_shared
from ._client_command_runner import run_client_command_spec as run_client_command_spec_shared
from ._validation import invalid_argument

session_app = typer.Typer(help="Session information commands", no_args_is_help=True)


SessionCommandSpec = CommandSpec


SESSION_INFO_SPEC = SessionCommandSpec(
    command_name="session info",
    client_method="get_session_info",
)
SESSION_SNAPSHOT_SPEC = SessionCommandSpec(
    command_name="session snapshot",
    client_method="session_snapshot",
)
SESSION_STOP_ALL_CLIPS_SPEC = SessionCommandSpec(
    command_name="session stop-all-clips",
    client_method="stop_all_clips",
)


def run_client_command(
    ctx: typer.Context,
    *,
    command_name: str,
    args: dict[str, object],
    fn: Callable[[object], dict[str, object]],
) -> None:
    run_client_command_shared(
        ctx,
        command_name=command_name,
        args=args,
        fn=fn,
        get_client_fn=get_client,
        execute_command_fn=execute_command,
    )


def run_client_command_spec(
    ctx: typer.Context,
    *,
    spec: SessionCommandSpec,
    args: dict[str, object],
    method_kwargs: dict[str, object] | Callable[[], dict[str, object]] | None = None,
) -> None:
    run_client_command_spec_shared(
        ctx,
        spec=spec,
        args=args,
        method_kwargs=method_kwargs,
        get_client_fn=get_client,
        execute_command_fn=execute_command,
    )


@session_app.command("info")
def session_info(ctx: typer.Context) -> None:
    run_client_command_spec(
        ctx,
        spec=SESSION_INFO_SPEC,
        args={},
    )


@session_app.command("snapshot")
def session_snapshot(ctx: typer.Context) -> None:
    run_client_command_spec(
        ctx,
        spec=SESSION_SNAPSHOT_SPEC,
        args={},
    )


def _load_snapshot(path: str, *, source_name: str) -> dict[str, object]:
    snapshot_path = Path(path)
    try:
        raw = snapshot_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise invalid_argument(
            message=f"{source_name} file could not be read: {snapshot_path}",
            hint=f"Provide a readable UTF-8 JSON file for {source_name}.",
        ) from exc
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise invalid_argument(
            message=f"{source_name} file must be valid JSON: {exc.msg}",
            hint=f"Fix JSON syntax in {snapshot_path}.",
        ) from exc
    if not isinstance(payload, dict):
        raise invalid_argument(
            message=f"{source_name} snapshot root must be an object",
            hint="Use object JSON snapshots generated by session snapshot.",
        )
    return payload


def _session_diff_result(*, from_path: str, to_path: str) -> dict[str, object]:
    from_snapshot = _load_snapshot(from_path, source_name="--from")
    to_snapshot = _load_snapshot(to_path, source_name="--to")
    result = compute_session_diff(from_snapshot, to_snapshot)
    return {
        "from_path": str(Path(from_path)),
        "to_path": str(Path(to_path)),
        **result,
    }


@session_app.command("diff")
def session_diff(
    ctx: typer.Context,
    from_path: str = typer.Option(..., "--from"),
    to_path: str = typer.Option(..., "--to"),
) -> None:  # noqa: E501
    run_client_command(
        ctx,
        command_name="session diff",
        args={"from": from_path, "to": to_path},
        fn=lambda _client: _session_diff_result(from_path=from_path, to_path=to_path),
    )


@session_app.command("stop-all-clips")
def session_stop_all_clips(ctx: typer.Context) -> None:
    run_client_command_spec(
        ctx,
        spec=SESSION_STOP_ALL_CLIPS_SPEC,
        args={},
    )


def register(app: typer.Typer) -> None:
    app.add_typer(session_app, name="session")
