from __future__ import annotations

import json
from pathlib import Path

import typer

from ..runtime import execute_command, get_client
from ..session_diff import compute_session_diff
from ._validation import invalid_argument

session_app = typer.Typer(help="Session information commands", no_args_is_help=True)


@session_app.command("info")
def session_info(ctx: typer.Context) -> None:
    execute_command(
        ctx,
        command="session info",
        args={},
        action=lambda: get_client(ctx).get_session_info(),
    )


@session_app.command("snapshot")
def session_snapshot(ctx: typer.Context) -> None:
    execute_command(
        ctx,
        command="session snapshot",
        args={},
        action=lambda: get_client(ctx).session_snapshot(),
    )


def _load_snapshot(path: str, *, source_name: str) -> dict[str, object]:
    snapshot_path = Path(path)
    try:
        raw = snapshot_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise invalid_argument(
            message=f"{source_name} file could not be read: {snapshot_path}",
            hint=f"Provide a readable UTF-8 JSON file for {source_name}.",
        ) from exc
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise invalid_argument(
            message=f"{source_name} file must be valid JSON: {exc.msg}",
            hint=f"Fix JSON syntax in {snapshot_path}.",
        ) from exc
    if not isinstance(payload, dict):
        raise invalid_argument(
            message=f"{source_name} snapshot root must be an object",
            hint="Use object JSON snapshots generated by session snapshot.",
        )
    return payload


@session_app.command("diff")
def session_diff(
    ctx: typer.Context,
    from_path: str = typer.Option(..., "--from"),
    to_path: str = typer.Option(..., "--to"),
) -> None:  # noqa: E501
    def _run() -> dict[str, object]:
        from_snapshot = _load_snapshot(from_path, source_name="--from")
        to_snapshot = _load_snapshot(to_path, source_name="--to")
        result = compute_session_diff(from_snapshot, to_snapshot)
        return {
            "from_path": str(Path(from_path)),
            "to_path": str(Path(to_path)),
            **result,
        }

    execute_command(
        ctx,
        command="session diff",
        args={"from": from_path, "to": to_path},
        action=_run,
    )


@session_app.command("stop-all-clips")
def session_stop_all_clips(ctx: typer.Context) -> None:
    execute_command(
        ctx,
        command="session stop-all-clips",
        args={},
        action=lambda: get_client(ctx).stop_all_clips(),
    )


def register(app: typer.Typer) -> None:
    app.add_typer(session_app, name="session")
