"""Generate the pass-through client methods from the descriptor table.

Writes ``src/ableton_cli/client/_client_generated.py``. The output is checked
in and CI regenerates it and fails on any diff, the same contract
``tools/generate_skill_docs.py`` already uses. Nothing is resolved at runtime:
the generated file is ordinary, readable, type-annotated Python that a reader
can step through and an IDE can complete.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
# Running this as a script puts tools/ on sys.path, not the repo root.
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from ableton_cli.command_registry import (  # noqa: E402
    CLIENT_METHOD_SPECS,
    ClientMethodSpec,
)

_OUTPUT_PATH = _REPO_ROOT / "src" / "ableton_cli" / "client" / "_client_generated.py"

_HEADER = '''"""Generated by tools/generate_client_methods.py. Do not edit.

Every method here is a pass-through: it forwards its arguments to a remote
command and returns the response untouched. The source of truth is
``CLIENT_METHOD_SPECS`` in ``ableton_cli.command_registry``; regenerate with::

    uv run python tools/generate_client_methods.py

Client methods that assemble arguments, branch, or post-process are not
generated — they live hand-written in the sibling ``_client_*`` mixins.
"""

from __future__ import annotations

from typing import Any

from ..refs import RefPayload

__all__ = ["_AbletonClientGeneratedMixin"]


class _AbletonClientGeneratedMixin:
    """Pass-through remote calls. See module docstring."""

    _call: Any
'''


def _render_method(spec: ClientMethodSpec) -> str:
    signature_parts = ["self"]
    for param in spec.params:
        rendered = f"{param.name}: {param.annotation}"
        if param.default is not None:
            rendered += f" = {param.default}"
        signature_parts.append(rendered)
    signature = ", ".join(signature_parts)

    if spec.params:
        payload = (
            "{" + ", ".join(f'"{param.payload_key}": {param.name}' for param in spec.params) + "}"
        )
        body = f'return self._call("{spec.remote_command}", {payload})'
    else:
        body = f'return self._call("{spec.remote_command}")'

    return f"    def {spec.remote_command}({signature}) -> {spec.returns}:\n        {body}\n"


def render_module() -> str:
    parts = [_HEADER]
    for spec in sorted(CLIENT_METHOD_SPECS, key=lambda item: item.remote_command):
        parts.append("\n" + _render_method(spec))
    return "".join(parts)


def main() -> int:
    _OUTPUT_PATH.write_text(render_module(), encoding="utf-8")
    # Long signatures and payloads need wrapping; let the formatter own that
    # rather than reimplementing line-breaking here.
    subprocess.run(
        ["uv", "run", "ruff", "format", str(_OUTPUT_PATH)],
        cwd=_REPO_ROOT,
        check=True,
        capture_output=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
