from __future__ import annotations

import json
import socketserver
import threading
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from .command_backend import PROTOCOL_VERSION, RemoteErrorCode
from .events import Subscription

_REQUEST_KEYS = {"type", "name", "args", "meta", "request_id", "protocol_version"}
_REQUEST_TYPES = ("command", "subscribe")

#: How long a streaming connection waits for the next event before checking
#: whether the server is shutting down.
_EVENT_POLL_INTERVAL_S = 0.25

EventSubscriber = Callable[[dict[str, Any], dict[str, Any]], Subscription]


@dataclass(slots=True)
class CommandExecutionError(Exception):
    code: str
    message: str
    hint: str | None = None
    details: dict[str, Any] | None = None


def _ok(request_id: str, result: dict[str, Any]) -> dict[str, Any]:
    return {
        "ok": True,
        "request_id": request_id,
        "protocol_version": PROTOCOL_VERSION,
        "result": result,
        "error": None,
    }


def _error(
    request_id: str,
    code: str,
    message: str,
    hint: str | None = None,
    details: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "ok": False,
        "request_id": request_id,
        "protocol_version": PROTOCOL_VERSION,
        "result": None,
        "error": {
            "code": code,
            "message": message,
            "hint": hint,
            "details": details,
        },
    }


def _invalid_request(message: str, hint: str) -> CommandExecutionError:
    return CommandExecutionError(
        code=RemoteErrorCode.INVALID_ARGUMENT.value,
        message=message,
        hint=hint,
    )


def _request_id_from_payload(payload: Any) -> str:
    if not isinstance(payload, dict):
        return "unknown"
    request_id = payload.get("request_id")
    if not isinstance(request_id, str) or not request_id:
        return "unknown"
    return request_id


def _parse_command_request(
    payload: Any,
) -> tuple[str, str, str, dict[str, Any], dict[str, Any]]:
    if not isinstance(payload, dict):
        raise _invalid_request(
            message="Request payload must be an object",
            hint="Send one JSON object per line.",
        )

    missing = _REQUEST_KEYS.difference(payload)
    if missing:
        raise _invalid_request(
            message=f"Request payload is missing keys: {sorted(missing)}",
            hint="Use the CLI protocol request shape.",
        )
    extra = set(payload).difference(_REQUEST_KEYS)
    if extra:
        raise _invalid_request(
            message=f"Request payload has unexpected keys: {sorted(extra)}",
            hint="Send only the stable request protocol fields.",
        )

    request_id = payload.get("request_id")
    if not isinstance(request_id, str) or not request_id:
        raise _invalid_request(
            message="request_id must be a non-empty string",
            hint="Pass the request_id generated by the CLI.",
        )

    request_type = payload.get("type")
    if request_type not in _REQUEST_TYPES:
        raise _invalid_request(
            message=f"type must be one of {list(_REQUEST_TYPES)}",
            hint="Use the CLI protocol request shape.",
        )

    protocol_version = payload.get("protocol_version")
    if type(protocol_version) is not int or protocol_version < 1:
        raise _invalid_request(
            message="protocol_version must be a positive integer",
            hint="Use the CLI protocol request shape.",
        )
    if protocol_version != PROTOCOL_VERSION:
        raise CommandExecutionError(
            code=RemoteErrorCode.PROTOCOL_VERSION_MISMATCH.value,
            message=(
                f"Protocol version mismatch (remote={PROTOCOL_VERSION}, request={protocol_version})"
            ),
            hint=(
                "Align protocol_version between CLI and Remote Script "
                "(--protocol-version or 'ableton-cli config set protocol_version <n>')."
            ),
        )

    name = payload.get("name")
    if not isinstance(name, str) or not name:
        raise _invalid_request(
            message="name must be a non-empty string",
            hint="Pass a supported remote command name.",
        )

    args = payload.get("args")
    if not isinstance(args, dict):
        raise _invalid_request(
            message="args must be an object",
            hint="Pass a JSON object for args.",
        )

    meta = payload.get("meta")
    if not isinstance(meta, dict):
        raise _invalid_request(
            message="meta must be an object",
            hint="Pass a JSON object for meta.",
        )

    return request_id, str(request_type), name, args, meta


class _CommandTCPServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True

    def __init__(
        self,
        server_address: tuple[str, int],
        request_handler: type[socketserver.StreamRequestHandler],
        command_executor: Callable[[str, dict[str, Any], dict[str, Any]], dict[str, Any]],
        event_subscriber: EventSubscriber | None = None,
    ) -> None:
        self.command_executor = command_executor
        self.event_subscriber = event_subscriber
        self.stopping = threading.Event()
        super().__init__(server_address, request_handler)


class _Handler(socketserver.StreamRequestHandler):
    def handle(self) -> None:
        while True:
            raw = self.rfile.readline()
            if not raw:
                return

            keep_open, response, subscription = self._handle_line(raw)
            self._write_response(response)
            if subscription is not None:
                self._stream_events(subscription)
                return
            if not keep_open:
                return

    def _stream_events(self, subscription: Subscription) -> None:
        """Serve events until the client goes away or the server stops.

        A subscribing connection becomes an event stream: it stops reading
        requests, so an interleaved command can never be silently ignored
        while the socket is busy pushing.
        """
        server = self.server
        stopping = getattr(server, "stopping", None)
        try:
            while stopping is None or not stopping.is_set():
                received = subscription.get(timeout=_EVENT_POLL_INTERVAL_S)
                if received is None:
                    continue
                event, dropped = received
                self._write_response(
                    event.to_line_payload(
                        protocol_version=PROTOCOL_VERSION,
                        dropped=dropped,
                    )
                )
        except OSError:
            return
        finally:
            subscription.close()
            unsubscribe = getattr(server, "event_unsubscriber", None)
            if callable(unsubscribe):
                unsubscribe(subscription)

    def _subscribe(
        self, request_id: str, args: dict[str, Any], meta: dict[str, Any]
    ) -> tuple[dict[str, Any], Subscription]:
        server = self.server
        subscriber = getattr(server, "event_subscriber", None)
        if not callable(subscriber):
            raise CommandExecutionError(
                code=RemoteErrorCode.INVALID_ARGUMENT.value,
                message="This Remote Script does not serve event subscriptions",
                hint="Reinstall the Remote Script with 'ableton-cli install-remote-script --yes'.",
            )
        subscription = subscriber(args, meta)
        result = {
            "subscribed": sorted(subscription.events),
            "stream": True,
        }
        return _ok(request_id=request_id, result=result), subscription

    def _handle_line(self, raw: bytes) -> tuple[bool, dict[str, Any], Subscription | None]:
        try:
            payload = json.loads(raw.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            # The line could not be decoded, so framing may be corrupt for
            # the rest of the stream; close the connection rather than keep
            # reading lines that may no longer align to request boundaries.
            return (
                False,
                _error(
                    request_id="unknown",
                    code=RemoteErrorCode.INVALID_ARGUMENT.value,
                    message="Request line is not valid JSON",
                    hint="Send one JSON object per line.",
                ),
                None,
            )

        request_id = _request_id_from_payload(payload)

        subscription: Subscription | None = None
        try:
            request_id, request_type, name, args, meta = _parse_command_request(payload)

            server = self.server
            if not isinstance(server, _CommandTCPServer):
                raise RuntimeError("Invalid server type")

            if request_type == "subscribe":
                response, subscription = self._subscribe(request_id, args, meta)
            else:
                result = server.command_executor(name, args, meta)
                response = _ok(request_id=request_id, result=result)
        except CommandExecutionError as exc:
            response = _error(
                request_id=request_id,
                code=exc.code,
                message=exc.message,
                hint=exc.hint,
                details=exc.details,
            )
        except Exception as exc:  # noqa: BLE001
            response = _error(
                request_id=request_id,
                code=RemoteErrorCode.INTERNAL_ERROR.value,
                message=f"Remote internal error: {exc}",
                hint="Check Remote Script logs.",
            )

        return True, response, subscription

    def _write_response(self, payload: dict[str, Any]) -> None:
        self.wfile.write((json.dumps(payload) + "\n").encode("utf-8"))
        self.wfile.flush()


class AbletonCommandServer:
    def __init__(
        self,
        host: str,
        port: int,
        command_executor: Callable[[str, dict[str, Any], dict[str, Any]], dict[str, Any]],
        event_subscriber: EventSubscriber | None = None,
        event_unsubscriber: Callable[[Subscription], None] | None = None,
    ) -> None:
        self._host = host
        self._port = port
        self._command_executor = command_executor
        self._event_subscriber = event_subscriber
        self._event_unsubscriber = event_unsubscriber
        self._server: _CommandTCPServer | None = None
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        if self._thread is not None and self._thread.is_alive():
            return

        self._server = _CommandTCPServer(
            (self._host, self._port),
            _Handler,
            command_executor=self._command_executor,
            event_subscriber=self._event_subscriber,
        )
        self._server.event_unsubscriber = self._event_unsubscriber
        self._thread = threading.Thread(
            target=self._server.serve_forever,
            name="ableton-cli-remote",
            daemon=True,
        )
        self._thread.start()

    def stop(self) -> None:
        if self._server is None:
            return

        self._server.stopping.set()
        self._server.shutdown()
        self._server.server_close()

        if self._thread is not None:
            self._thread.join(timeout=1.0)

        self._server = None
        self._thread = None
